sudo: required
services:
- docker
before_install:
- docker build -t lrx0014/examsys .
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
env:
  matrix:
  - secure: Nvu/13zOgpCGLxqAq3m9s408ti75+rj0CbVsW7LSuSZ6sZAuDzf7KZdmHPwMOOOsQk0VfPI7pZUUsK/LTyuRveZ+GUtSSZ7Ax6/8C1KhsqDLXrywHByDtlVabZ9S3CH4VTtfSBC2PSlJ3m23GYN0ZZqoyI4MrJgKbcw2k/jA6QayJnmxDhOmXQar80zco6g6qohdZ9r8a69WFdZ3twZ68G1sQxA1dl4YAoqrBLFOEluW0kzbv/n/NVqLS2vNb8vm/iXsGIuPIcw2VK6QEUZLgIdfPyB10kuiNEVHp+9JsXPLtH8nyT26cgXP2AaBTRIiik65vdFa4P8TZcYH8jqOzTyjlKk/yEoujsC7DHrKWNJ2aL5QIDEDpzRF9+bFbyZpaU9ffDbHNhhDG5VFrsAr7/fk21ey2+6fTjDVB6oXKal81P8501KFNQjnCVIO3A3ek12oNvSuylUd1GbQrWGeHMiYzX/AYTx456Rw1M40bCdD5OV52eD07OEbXwRMHbGbXs54iMUVUZPkjjaQnvpxz0pn7zz2iB8NZ/yDD95Fdt3KS2/axiS92mgvjRmdLhL5xTbaks+grTlMX9IVy9vsuqfACez1KsjMBZQTvWjTWtDNi0iNBInxOteIubgk2u+klpzc6PvZfoQX6mTLnPRDeVSNxQC/gHm5w061aICDy+8=
  - secure: Fj06JQoIdSmv0DZ2FYQQzBppB18jxsUhACcVuEAAP0fVAu9WQDLYMh3jRgEUFrBT8fT91wgtmJIeISV3a/AXvzfhEwRvduXS5NgIQy9V9+BHzIlq0GPdd4VFARgiTczlrkGisOgsiJuauoL12MTOfLXGqSZIfBpWhmKdGabQ4M1n4mVabarN1kO54t29X5rZK0t9NKD4B8tqbjvuQKMyeh0WrBaLe/jlFzho38ybnGGtCwwuFT4pgYoj8MGiqN6kcUE0uGzX3GixXwJDnSFM+D6FTgkWdUZaOCmhgrDeE5aOQbWgCKTaVYozsda1ooHeoJdqkV2j61COWn9cVF5gLXVASTlRr11omDZrLy1WO+w2GH9e5b9cKW1pV+KX3v6COJRr3/7yBLcXJCqVxFetMJn282cRZ5IWwmBBg5MmeSYFN0c4+9okqg4OR9oyf1ocm+jbGqR2Ls6sYfMfQg04Vh/KcAS768DxOsfRVfB+kvaoKlrUxsHNNWwwejkp69cPeIdPvs1JrEcPDuRi5dGndZFAbJEeI3AD7wy3BufbBcIlUSWZcVI0hXfeMTdS4sYvmC69qlJ6ysYy8Vrm92OeD2rjPPdrlPS4ffmvpBK/GaQwJOn7xpCOttPZB9oV01hzpigwDtWIXZS1P7nW3fPIIeyr0iZLp7fKXdW7oqES0PA=
